{{- if and .Values.mft.enabled .Values.ingress.enabled .Values.mft.ingress.host }}
{{- if eq .Values.tls.provider "cert-manager" }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mft-tls-cert
  namespace: {{ include "vtom.namespace" . }}
  labels:
    app.kubernetes.io/name: mft
    {{- include "vtom.labels" . | nindent 4 }}
spec:
  secretName: mft-tls-secret
  issuerRef:
    name: {{ .Values.tls.certManager.clusterIssuer }}
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - {{ .Values.mft.ingress.host | quote }}
{{- end }}

{{- if eq .Values.ingress.className "traefik" }}
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: mft-skip-tls-verify
  namespace: {{ include "vtom.namespace" . }}
  labels:
    {{- include "vtom.labels" . | nindent 4 }}
spec:
  insecureSkipVerify: true
{{- end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mft-ingress
  namespace: {{ include "vtom.namespace" . }}
  labels:
    app.kubernetes.io/name: mft
    {{- include "vtom.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.ingress.className "traefik" }}
    traefik.ingress.kubernetes.io/service.serversscheme: "https"
    {{- if .Values.ingress.httpsRedirect }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ include "vtom.namespace" . }}-redirect-https@kubernetescrd
    {{- end }}
    {{- end }}
    {{- with .Values.mft.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.mft.ingress.host | quote }}
      secretName: {{ if eq .Values.tls.provider "secret" }}{{ .Values.tls.secret.mft }}{{ else }}mft-tls-secret{{ end }}
  {{- end }}
  rules:
    - host: {{ .Values.mft.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mft
                port:
                  number: {{ .Values.mft.ports.https }}
{{- end }}
